package com.hackthon.teamwg.projects.services;

import com.hackthon.teamwg.projects.services.RaasRestService.*;
import static org.hamcrest.CoreMatchers.*;
import static org.junit.Assert.*;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.ws.rs.Consumes;
import javax.ws.rs.DefaultValue;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.QueryParam;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import org.apache.log4j.Logger;
import com.hackthon.teamwg.projects.dao.GeneralClass;
import com.hackthon.teamwg.projects.dao.RaasServicesDAO;
import com.hackthon.teamwg.projects.dto.RaasGenericCountDTO;
import com.hackthon.teamwg.projects.dto.RaasTasksDTO;
import com.hackthon.teamwg.projects.dto.RaasUsersDTO;
public class RaasRestServiceTest {

	@Test
	public void type() throws Exception {
		// TODO auto-generated by JUnit Helper.
		assertThat(RaasRestService.class, notNullValue());
	}

	@Test
	public void instantiation() throws Exception {
		// TODO auto-generated by JUnit Helper.
		RaasRestService target = new RaasRestService();
		assertThat(target, notNullValue());
	}

	@Test
	public void getUser_A$String() throws Exception {
		// TODO auto-generated by JUnit Helper.
		RaasRestService target = new RaasRestService();
		String loginId = null;
		Response actual = target.getUser(loginId);
		assertNotNull(actual);
	}

	@Test
	public void getSlaExpiredTasks_A$String$Integer() throws Exception {
		// TODO auto-generated by JUnit Helper.
		RaasRestService target = new RaasRestService();
		String groupName = null;
		Integer page_no = null;
		Response actual = target.getSlaExpiredTasks(groupName, page_no);
		assertNotNull(actual);
	}

	@Test
	public void getUnassignedGroupTasks_A$String$Integer() throws Exception {
		// TODO auto-generated by JUnit Helper.
		RaasRestService target = new RaasRestService();
		String groupName = null;
		Integer page_no = null;
		Response actual = target.getUnassignedGroupTasks(groupName, page_no);
		assertNotNull(actual);
	}

	@Test
	public void getUnassignedTasksForManager_A$String$Integer() throws Exception {
		// TODO auto-generated by JUnit Helper.
		RaasRestService target = new RaasRestService();
		String managerName = null;
		Integer page_no = null;
		Response actual = target.getUnassignedTasksForManager(managerName, page_no);
		assertNotNull(actual);
	}

	@Test
	public void createTask_A$RaasTasksDTO() throws Exception {
		// TODO auto-generated by JUnit Helper.
		RaasRestService target = new RaasRestService();
		RaasTasksDTO tasksDTO = null;
		Response actual = target.createTask(tasksDTO);
		assertNotNull(actual);
	}

	@Test
	public void getUserStatusOfManager_A$String() throws Exception {
		// TODO auto-generated by JUnit Helper.
		RaasRestService target = new RaasRestService();
		String managerName = null;
		Response actual = target.getUserStatusOfManager(managerName);
		assertNotNull(actual);
	}

	@Test
	public void getUserStatusOfManager_A$String$String() throws Exception {
		// TODO auto-generated by JUnit Helper.
		RaasRestService target = new RaasRestService();
		String managerName = null;
		String groupName = null;
		Response actual = target.getUserStatusOfManager(managerName, groupName);
		assertNotNull(actual);
	}

	@Test
	public void getUserSatisfaction_A$String$String() throws Exception {
		// TODO auto-generated by JUnit Helper.
		RaasRestService target = new RaasRestService();
		String managerName = null;
		String groupName = null;
		Response actual = target.getUserSatisfaction(managerName, groupName);
		assertNotNull(actual);
	}

}
